#!/bin/sh

##
## Prints simple stats about a given port committer
##

[ -n "$1" ] || ! echo "Usage: $0 user-name" || exit 1

([ -f /tmp/svn.log ] && cat /tmp/svn.log ||
 (echo "downloading the SVN log, please wait ..." >&2 ; svn log https://svn.FreeBSD.org/ports/head | tee /tmp/svn.log)) | awk \
'
  BEGIN {
    inrec=0
    cnt=0
    cntm=0
  }
  / \| '$1' \| / {
    cnt++
    if (date2 == "")
      date2 = $5
    date1=$5
    inrec=1
    next
  }
  /^Approved by:.*\(mentor\).*/ {
    if (inrec)
      cntm++;
    next
  }
  / \| [a-z0-9]+ \| / {
    inrec=0
    next
  }
  END {
    if (cnt > 0) {
      print "date-range=",date1,"-",date2, "lifetime-commits=",cnt, "mentored-commits=",cntm
    } else {
      print "No commits by","'$1'","found"
    }
  }
'
